title = 'Scam Defenders'
description = 'Tips and resources for helping protect the people you care about from online scams. These scams are constantly evolving and there is no foolproof way of stopping them but here are some ways to help.'
baseURL = 'https://scamdefenders.net/'
languageCode = 'en-us'
theme = 'archie'
enableEmoji = true
enableGitInfo = true
disableKinds = ["taxonomy"]

[frontmatter]
    lastmod = ["lastmod", ":git"]

[params]
    mode = 'auto'
    subtitle = 'Tips and resources for helping protect the people you care about from online scams.'
    customcss = ["custom.css"]
    og_image = "og-image.png"

[sitemap]
    changeFreq = 'weekly'


[[menu.main]]
name = "📰 Scam Prevention News"
url = "/news"
weight = 1